import turtle
#En kommentar?
def draw_hexagon(t):
    t.forward(100)
    t.right(60)
    t.forward(100)
    t.right(60)
    t.forward(100)
    t.right(60)
    t.forward(100)
    t.right(60)
    t.forward(100)
    t.right(60)
    t.forward(100)
    t.right(60)

turtle.penup()
turtle.goto(-150, -100)
turtle.pendown()
turtle.left(90)
draw_hexagon(turtle)
turtle.penup()
turtle.setx(turtle.xcor()+173)
turtle.pendown()
draw_hexagon(turtle)
turtle.penup()
turtle.sety(turtle.ycor()+200)
turtle.pendown()
draw_hexagon(turtle)
turtle.penup()
turtle.setx(turtle.xcor()-173)
turtle.pendown()
draw_hexagon(turtle)
turtle.done()
