import turtle

turtle.setup(500, 500)
turtle.circle(40)
turtle.penup()
turtle.forward(80)
turtle.pendown()
turtle.circle(40)
turtle.penup()
turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.pendown()
turtle.circle(40)
turtle.penup()
turtle.left(180)
turtle.forward(80)
turtle.left(180)
turtle.pendown()
turtle.circle(40)
turtle.done()
